config/routes.rb
Rails.application.routes.draw do

  resources :users
  resource :session
  resources :subs do
    resources :posts
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :sub_id, :author_id, presence: true

  belongs_to :author,
    foreign_key: :author_id,
    primary_key: :id,
    class_name: 'User'

  belongs_to :sub,
    foreign_key: :sub_id,
    primary_key: :id,
    class_name: 'Sub'
end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true
  validates :title, uniqueness: true

  has_many :posts

  belongs_to :moderator,
    class_name: 'User',
    foreign_key: :moderator_id,
    primary_key: :id

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string           not null
#  email           :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  session_token   :string           not null
#

class User < ActiveRecord::Base
  validates :name, :email, :password_digest, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :subs,
    class_name: 'Sub',
    foreign_key: :moderator_id,
    primary_key: :id

  has_many :posts,
    class_name: 'Post',
    foreign_key: :author_id,
    primary_key: :id

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    @user = User.find_by_email(email)
    if @user.is_password?(password)
      @user
    else
      nil
    end
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login(user)
    session[:session_token] = user.session_token
  end

  def logged_in?(user)
    current_user == user
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :is_author?, only: [:edit, :update]

  def show
    @post = Post.find_by_id(params[:id])
    render :show
  end

  def new
    @post = Post.new
    render :new
  end

  def edit
    @post = Post.find_by_id(params[:id])
    render :edit
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to sub_post_url(@post.sub, @post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def update
    @post = Post.find_by_id(params[:id])
    if @post.update_attributes(post_params)
      redirect_to sub_post_url(@post.sub, @post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    if @post.destroy
      redirect_to sub_url(Sub.find_by_id(@post.sub_id))
    else
      flash.now[:errors] = @post.errors.full_messages
      render :show
    end
  end

  private

  def is_author?
    current_user.id == Post.find_by_id(params[:id]).author_id
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id, :author_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    login(@user)
    redirect_to user_url(@user)
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :check_mod?, only: [:edit, :update]

  def index
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = Sub.find_by_id(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by_id(params[:id])
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def show
    render :show
  end

  private

  def check_mod?
    current_user.id == Sub.find_by(id: params[:id])
  end

  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def show
    render :show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find_by(session_token: session[:session_token])
    render :edit
  end

  def update
    @user = User.find_by(session_token: session[:session_token])
    if @user.update_attributes(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if !current_user.nil? %>
    <%= button_to "Logout", session_url, method: :delete %>
  <% end %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<% url = post.persisted? ? sub_post_url(post.sub, post) : sub_posts_url %>
<% method = post.persisted? ? "PATCH" : "POST" %>
<% button_text = post.persisted? ? "Update" : "Create" %>
<%= flash.now[:errors] %>
<form action="<%= url %>" method="POST">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="post[author_id]" value="<%= current_user.id %>">
  <input type="hidden" name="post[sub_id]" value="<%= params[:sub_id] %>">
  <label>Title
  <input type="text" name="post[title]" value="<%= post.title %>">
  </label>
  <br>
  <label>URL
  <input type="text" name="post[url]" value="<%= post.url %>">
  </label>
  <br>
  <label>Content
  <input type="textarea" name="post[content]" value="<%= post.content %>">
  </label>
  <br>
  <input type="submit" value="<%= button_text %>">
</form>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<% @post = Post.find_by_id(params[:id]) %>
<h2><a href="<%= @post.url %>"><%= @post.title %></a></h2>
<br>
<p><%= @post.content %></p>
<br>
<br>
<%= button_to "Edit post", edit_sub_post_url(@post.sub, @post), method: :get %>
<br>
<%= button_to "Sub", sub_url(Sub.find_by_id(@post.sub_id)), method: :get %>
<br>
<%= button_to "Author", user_url(User.find_by_id(@post.author_id)), method: :get %>
<br>
<%= button_to "Delete post", sub_post_url(@post.sub, @post), method: :delete %>

app/views/subs/_form.html.erb
<% url = sub.persisted? ? sub_url(sub) : subs_url %>
<% method = sub.persisted? ? "PATCH" : "POST" %>
<% button_text = sub.persisted? ? "Update" : "Create" %>
<form action="<%= url %>" method="POST">
  <input type="hidden" name="_method" value="<%= method %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="sub[moderator_id]" value="<%= current_user.id %>">
  <label>Title
  <input type="text" name="sub[title]" value="<%= sub.title %>">
  </label>
  <br>
  <label>Description
  <input type="textarea" name="sub[description]" value="<%= sub.description %>">
  </label>
  <br>
  <input type="submit" value="<%= button_text %>">
</form>

app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<%= render "form", sub: @sub %>

app/views/subs/new.html.erb
<h2>Create a Sub</h2>

<%= flash.now[:errors] %>

<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<% @sub = Sub.find_by_id(params[:id]) %>
<h2><%= @sub.title %></h2>
<br>

<% @sub.posts.each do |post| %>
  <li><a href="<%= sub_post_url(post.sub, post) %>"><%= post.title %></a></li>
<% end %>

<%= button_to "Add post", new_sub_post_url(@sub), method: :get %>
<br>
<%= button_to "Edit sub", edit_sub_url(@sub), method: :get %>
<br>
<%= button_to "Moderator", user_url(User.find_by_id(@sub.moderator_id)), method: :get %>

app/views/users/_form.html.erb
<% url = @user.persisted? ? user_url(@user) : users_url %>
<% method = @user.persisted? ? "PATCH" : "POST" %>
<% button_text = @user.persisted? ? "Update" : "Create" %>

<form action="<%= url %>" method="POST">
  <input type="hidden" name="_method" method="<%= method %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Name
  <input type="text" name="user[name]" value="<%= @user.name %>">
  </label>
  <label>Email
  <input type="text" name="user[email]" value="<%= @user.email %>">
  </label>
  <label>Password
  <input type="text" name="user[password]">
  </label>

  <input type="submit" value="<%= button_text %>">
</form>

app/views/users/new.html.erb
<h1>Create User</h1>
<%= render "form", user: @user %>

app/views/users/show.html.erb
<% @user = User.find_by_id(params[:id]) %>
<h2> <%= @user.name %></h2>

<h3>Moderated Subs</h3>
<ul>
<% @user.subs.each do |sub| %>
  <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
<% end %>
</ul>
<br>
<%= button_to "Create sub", new_sub_url, method: :get %>

<h3>Authored Posts</h3>
<ul>
<% @user.posts.each do |post| %>
  <li><a href="<%= sub_post_url(post.sub, post) %>"><%= post.title %></a></li>
<% end %>
</ul>